### ISSUE TITLE
FR- Multicast Support

### ISSUE THREAD

**Issue by MRobi1** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#14]
I'm just learning about multicast support with zwavejs which makes setting notifications on multiple devices near instant. There's a thread on the inovelli forums about it right now. This is definitely something that you should look into implementing, it speeds things up considerably over using the bulk_set service. 

[https://community.inovelli.com/t/instant-notifications-all-switches-using-multicast-on-ha/9077/29](url)

**Comment by ryanjohnsontv** [comment]
This is awesome! I'll try to get it added within the next day or two. Thank you for letting me know about it.

**Comment by ryanjohnsontv** [comment]
Just added! I've only done limited testing on my switches but it worked perfectly. All that's needed now is to check "Use Multicast" on the given notification node and it will send the updated service call.
