### ISSUE TITLE
2x Config Button Scene Support

### ISSUE THREAD

**Issue by shablagu** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#26]
Hi, 

Is it possible to add support for the 2x config button press? Thanks!

**Comment by ryanjohnsontv** [comment]
Which switch are you using? I only have the LZW36 and LZW31-SN switches to test locally, and the LZW31-SN switch config button is limited to only 1x presses for scenes.

**Comment by shablagu** [comment]
LZ31-SN had a firmware change to enable a config 2x scene

https://support.inovelli.com/portal/en/kb/articles/firmware-change-log-lzw31-sn-dimmer-switch-red-series#V161_-_10192021

**Comment by ryanjohnsontv** [comment]
I’ll update my switches to test and have an update out very shortly, thank you!

**Comment by ryanjohnsontv** [comment]
Unfortunately after updating to 1.61 I'm not seeing any events being triggered by double tapping the config button. When you have the chance could you post your event info when double tapping the config button? This is what appears when I tap it once: 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/43426700/140633082-1ffd55d3-6f99-4d6f-a71a-8c761cf0ce93.png">

**Comment by shablagu** [comment]
So strange I'm not getting any events either with the config double click?
I'll post on the inovelli forums to see if there are any solutions. Thanks
for being so responsive!

**Comment by ryanjohnsontv** [comment]
Closing for now, but if anything else pops up either re-open this issue or create a new one, thank you!
