### ISSUE TITLE
Dim Level Status Effect

### ISSUE THREAD

**Issue by jerryac** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#27]
On the notification manager, is there any way to allow an option to have the dim level shown as one of the effect options?

**Comment by ryanjohnsontv** [comment]
Could you clarify what you mean? Currently there is an option for changing the brightness level and an option for choosing the desired effect.
<img width="478" alt="Screen Shot 2021-11-23 at 9 26 16 AM" src="https://user-images.githubusercontent.com/43426700/143053090-ccdb7f31-68f6-4d9a-b9ee-9a2f00a002ab.png">

**Comment by jerryac** [comment]
My use case here is that when I have an automation running, I change the LED color so others know the device is running an automation however, when I use this to change the LED color, it appears to override the LED dimmer level indicator (how far up the bar goes) and just applies the selected effect. 

To resolve this my request would be to add an effect that only changes the LED color but keeps the dimmer indicator level unchanged.  Hopefully that makes sense.
Thanks!

**Comment by ryanjohnsontv** [comment]
Ah gotcha, makes sense! I could be wrong, but in all of my experience the notifications use the entirety of the LED bar when active and don’t take into account the current dimmer level of the switch. One option that might work (only for solid effects) is to use the LED manager node to change the LED color of the bar to still have a visual reference to your automation running, and this would honor the current dim level of the switch.

**Comment by jerryac** [comment]
I did consider that however the drawback there is that I can't simple use the clear notification option on the notification manager to remove it, which is slick!    Not the end of the world I guess to have a separate flow to change it back to the previous color though.   Figured I'd check to see if it could be done.
