### ISSUE TITLE
New descriptions for nodes

### ISSUE THREAD

**Issue by Hilo4321** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#29]
Hi, after 5 minutes of (admittedly sleepy) pondering, I figured out what each of the LED nodes is for. Thought I'd offer a couple changes for clarity. Obviously feel free to change anything if you end up using these. Cheers and thanks for the awesome nodes!

**Inovelli Notification Manager**

This node allows you to set color, brightness, and effect type/duration for notifications on Inovelli Red switches. No manual calculation needed.

**Inovelli LED Manager**

This node allows you to set the color and brightness of the LED strip (not for notifications) on Inovelli Black and Red switches without looking up values manually.

**Comment by ryanjohnsontv** [comment]
Good call! Admittedly I haven’t checked those since the repo’s infancy so I agree they could definitely use some updating. Thank you!

**Comment by Hilo4321** [comment]
Cheers!
