### ISSUE TITLE
Zigbee Support

### ISSUE THREAD

**Issue by MRobi1** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#40]
With the blue series nearing launch, I'm wondering if you'd be willing to expand the capabilities of this set of nodes to support the new zigbee lineup as well? I think it would be easier to have it all in one palette rather than separate ones.

Thoughts?

**Comment by ryanjohnsontv** [comment]
Yes, I intend to! Ideally I would love to have a separate palette that covers all scene control devices like hue remotes, Zooz scenes, and all of the Inovelli scene options. I’ve started work on that but it would need a lot of user input to have a repository of button mappings for each device. I’m hoping to get one of each of the Inovelli blues when they’re released so I can test myself and get it added ASAP.

**Comment by MRobi1** [comment]
I'm not sure if you're on the inovelli community forums, but if so you should find me on there (MRobi) and we can take this out of the public eye. I may or may not have access to the info and Eric may or may not have given me the OK to get you whatever info you need to make it work with the blue series such as mapping and paremeters and such ;)

**Comment by sstarcher** [comment]
Any luck with this it would be great to see blue supported here
