### ISSUE TITLE
Scene Manager Not Working

### ISSUE THREAD

**Issue by MRobi1** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#5]
First, thank you for these awesome nodes! Just getting started with Z-Wave JS and controlling my inovelli switches was my biggest concern. These will make it simple!

I'm having an issue getting the scene manager node working.

I've got an events-all node listening to zwave_js_value_notification
When I double tap the switch, the events-all node is picking it up, confirmed with a debug node.
The scene manager node doesn't seem to be filtering the event though.
I've tried substituting the node_id for the entity_id but that didn't work. I see in the code it's looking for payload.event.node_id which I can see in the debug node is "2", but getting nothing output from the scene manager.

I'm sure it's just something I've got wrong somewhere
![Screenshot 2021-05-27 165627](https://user-images.githubusercontent.com/34860474/119889384-de003380-bf0c-11eb-8d9c-d68421917326.png)

**Comment by ryanjohnsontv** [comment]
I'm assuming I have it mapped incorrectly, as I didn't have any Dimmer  switches to test on and the documentation was lacking. Based on the values in your debug node the double tap is routing to the "Release Light Paddle" output. I hate to make you run through each scene to update the button mapping, so I'm going to do some digging online to see if I can find the right property_key and value_raw mappings, but if you have the time and want to update the mappings yourself I can push a fix for it immediately!

**Comment by ryanjohnsontv** [comment]
Updated here: https://github.com/ryanjohnsontv/node-red-contrib-ha-inovelli-manager/commit/2b3ade137ad853f07de5708b2a096d473adfde03
Let me know if this looks good for you and I'll push to npm !

**Comment by MRobi1** [comment]
I was creating a PR to do exactly that and put it in the wrong repository. The mapping still doesn't look right in the update.
1x = 0
2x = 3
3x = 4
4x = 5
5x = 6
hold = 2
release = 1

**Comment by ryanjohnsontv** [comment]
Just merged! I imagine the LZW30-SN will behave identically, and if so I can just have either switch use the same mapping. I actually have the LZW36 and tested everything so that mapping should be good as-is, but if not please let me know.

**Comment by MRobi1** [comment]
I've got the LZW30 and LZW36 so I'll test them all as I get them connected. I'll probably tackle changing everything over on the weekend. I assume the LZW30 will be the same mapping

**Comment by MRobi1** [comment]
LZW30-SN re-mapped. It does appear to be the same as the LZW31. 
You were right on the LZW36, mapping seems to be good as-is.
Now you just need someone to test the light strip, sorry I can't help on that one.

**Comment by ryanjohnsontv** [comment]
Just pushed a new release to npm so hopefully without the hour you’ll be able to update. Thank you so much for all your help!

**Comment by MRobi1** [comment]
No problem! These nodes are the best I've seen more managing the inovelli switches with node-red.
Have you posted them up on the inovelli community forums yet? I did a quick search earlier and didn't see any mention of it. There's people using multiple function nodes and switches to achieve the same thing. This could be very useful for a lot of people!
