### ISSUE TITLE
Red 2-1 Switch support?

### ISSUE THREAD

**Issue by Ccheese4** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#68]
is there any plan to add support for the new Red 2-1 switches? If not, I may look into contributing (though I'm not really up on Javascript, and I'd have no idea what I'm doing).

**Comment by UngluedChalice** [comment]
I would be happy to test with the new 2-1, but I also have zero coding experience.

**Comment by ryanjohnsontv** [comment]
I have a PR currently being worked on that adds the 2-1 Switch support: https://github.com/ryanjohnsontv/node-red-contrib-ha-inovelli-manager/pull/66
I'm hoping to have it done soon!

**Comment by jprasm** [comment]
Just got my first VZW31-SN, so I'm anxiously waiting for this update! Thank you so much for your work on this, my house depends on you :) 

I don't know if this is possible, but I have one node for the LZW31-SN dimmers (7 in my house), another node for the LZW30-SN on/off switches (16 in my house) and I'm worried I'm going to have another node for these new 2-1 switches! 

The reason I have that, is so all the switches in my house react the same way, no matter if they're a dimmer or a switch. 

Is there any way to have one node figure out the switch's product code so that it is all housed within one node? I might be asking too much here :) 

Thanks again. Please keep up the good work.

**Comment by ryanjohnsontv** [comment]
> Just got my first VZW31-SN, so I'm anxiously waiting for this update! Thank you so much for your work on this, my house depends on you :)
> 
> I don't know if this is possible, but I have one node for the LZW31-SN dimmers (7 in my house), another node for the LZW30-SN on/off switches (16 in my house) and I'm worried I'm going to have another node for these new 2-1 switches!
> 
> The reason I have that, is so all the switches in my house react the same way, no matter if they're a dimmer or a switch.
> 
> Is there any way to have one node figure out the switch's product code so that it is all housed within one node? I might be asking too much here :)
> 
> Thanks again. Please keep up the good work.

Unfortunately none of the Home Assistant integrations pass identifiable product information in the event message body, so you're stuck using just the dedicated node/device ID

**Comment by SethCalkins** [comment]
> I have a PR currently being worked on that adds the 2-1 Switch support: #66 I'm hoping to have it done soon!

I can test tonight --

**Comment by SethCalkins** [comment]
I added #69 to the mix here.

**Comment by zpearce2814** [comment]
It looks like a new parameter of 99 was used for the notification. Looking at the code it should may be an easy change?

Something like the needed to be added to the inputSwitchConver function:

        } else if (["dimmer", "vzw31", "vzw31-sn", 99].includes(parameter)) {
          parameter = 99;

And this needs to be changed in the HTML I believe
<div class="form-row">
    <label for="node-input-switchtype"><i class="icon-tag"></i>Switch Type</label>
    <select name="node-input-switchtype" id="node-input-switchtype">
        <option value="8">On/Off (LZW30-SN)</option>
        <option value="16">Dimmer (LZW31-SN)</option>
        <option value="24">Light Dimmer (LZW36)</option>
        <option value="25">Fan Dimmer (LZW36)</option>
        <option value="49">Fan & Light (LZW36)</option>
        _<option value="99">On\Off+Dimmer (VZW36-SN)</option>_
    </select>
  </div>

I assume the rest of the value would be the same as the existing switches.

**Comment by zpearce2814** [comment]
Any updates on this?

**Comment by jprasm** [comment]
everyone must be enjoying summer....

**Comment by UngluedChalice** [comment]
> I have a PR currently being worked on that adds the 2-1 Switch support: #66 I'm hoping to have it done soon!

Any updates perchance on this? :)

**Comment by jprasm** [comment]
Bueller?

**Comment by Rev-777** [comment]
Any update on this @ryanjohnsontv ? Thanks!

**Comment by zpearce2814** [comment]
@ryanjohnsontv I see that the Code has been updated in your pull request to work with the Red 2n1, Is this ready for testing? can we get a Beta Version to help Test?

**Comment by zpearce2814** [comment]
Is this project dead now?

**Comment by UngluedChalice** [comment]
I swear I saw somewhere that @ryanjohnsontv ordered some of the new Inovelli Red 2-1 switches - but now I can't find it so maybe I was dreaming?
