### ISSUE TITLE
Feature Request: Support for VZW31-SN LED Notifications

### ISSUE THREAD

**Issue by SethCalkins** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#69]
The new Inovelli Red's VZW31-SN can support changing the LEDs individually. Anyone interested in updating inovelli-led-manager?

You can select VZW31-SN from the dropdown:
https://inovelliusa.github.io/inovelli-switch-toolbox/

I'm willing to test test

**Comment by zpearce2814** [comment]
I second this, Got a new switch, and can setup my notifications. :(
